INSERT INTO `products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('How to Survive a Garden Gnome Attack', 'books', 17.50, 19);
INSERT INTO `products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('How to Teach Physics to Your Dog', 'books', 32.95, 4);
INSERT INTO `products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Goblin Proofing One\s Chicken Coop', 'books', 22.90, 22);
INSERT INTO `products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Highlights in the History of Concrete', 'books', 24.95, 311);
INSERT INTO `products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Managing a Dental Practice the Ghengis Khan Way', 'books', 26.99, 21);
INSERT INTO `products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Do Androids Dream of Electric Sheep?', 'books', 28.95, 61);
INSERT INTO `products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Attack of the Killer Tomatoes!', 'DVD', 18.95, 133);
INSERT INTO `products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Killer Klowns from Outer Space', 'DVD', 22.99, 72);
INSERT INTO `products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('The Perils of Gwendoline in the Land of the Yik Yak', 'DVD', 18.99, 61);
INSERT INTO `products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 'DVD', 21.95, 621);
INSERT INTO `products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Wookie Bath Robe, extra long', 'kitchen and bath', 89.95, 144);
INSERT INTO `products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Bread Cutter for Cat-Toast', 'kitchen and bath', 9.95, 861);
INSERT INTO `products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Cat Seat for Roomba', 'kitchen and bath', 34.95, 1016);
INSERT INTO `products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Shower Wine Glass Holder', 'kitchen and bath', 14.95, 4767);
INSERT INTO `products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('StormTrooper Oven Mitt', 'kitchen and bath', 16.95, 341);
INSERT INTO `products` (`product_name`, `department_name`, `price`, `stock_quantity`) VALUES ('Schrodinger Box - Cat not included', 'kitchen and bath', 14.99, 16242);
